extract_data:
  description: "Extract relevant data from the user input."
  expected_output: "A JSON object containing the extracted data."
  agent: "information_handler"

perform_crud:
  description: "Perform CRUD operations based on the extracted data."
  expected_output: "Result of the database operation."
  agent: "crud_handler"